#!/bin/bash

# Directory to monitor
DIR="/usr/share/polkit-1/actions"

# Loop over all files in the directory
for FILE in "$DIR"/*; do
    # Check if the FILE is a regular file and if it is, process it
    if [ -f "$FILE" ]; then
        # Use sed to replace any <allow_active> value with <allow_active>yes</allow_active> in the FILE
        if ! sed -i 's/<allow_active>.*<\/allow_active>/<allow_active>yes<\/allow_active>/g' "$FILE"; then
            echo "Error modifying file $FILE."
        fi
    fi
done

echo "The $DIR directory has been checked, and necessary files have been updated."
