#!/bin/bash

# Define path to the file
FILE="/lib/systemd/system/apparmor.service"
BACKUP="${FILE}.bak"

if [ -f "${BACKUP}" ] && grep -q "LiveKit Live CD" "${FILE}"; then
    mv -f "${BACKUP}" "${FILE}"
elif [ -f "${BACKUP}" ] && [ ! -f "${FILE}" ]; then
    rm "${BACKUP}"
fi

#DEBHELPER#
