#!/bin/bash
# preinst script for minios-boot

if [ -f /usr/lib/systemd/system/apparmor.service ] && [ ! -f /usr/lib/systemd/system/apparmor.service.bak ]; then
    mv /usr/lib/systemd/system/apparmor.service /usr/lib/systemd/system/apparmor.service.bak
fi
